version: 2.1
jobs:
  deploy_dialogflow_agent:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/repo/
    parameters:
      jsonKey:
        description: "The key json object specified in the environment variables."
        type: string # string? "${DEV_MDHS_CSA_KEY_JSON}"
      env:
        type: string # e.g. dev,
    steps:
      - checkout
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run: cd scripts && npm ci
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - scripts/node_modules
      - run:
          name: "Add env variables"
          command: cd scripts && echo "GOOGLE_APPLICATION_CREDENTIALS=./mdhs-key.json" > .env
      - run:
          name: "Create mdhs key file for scripts"
          command: cd scripts && echo "${<< parameters.jsonKey >>}" > mdhs-key.json
      - run:
          name: "Agent configuration"
          command: cd agent && mv agent.<< parameters.env >>.json agent.json
      - run:
          name: "Restore to << parameters.env >> Dialogflow"
          command: cd scripts && node restoreDialogflow
      - run:
          name: "Populate Firestore"
          command: cd scripts && node populateFirestore
  deploy_functions:
    docker:
      - image: circleci/node
    working_directory: ~/repo/
    parameters:
      firebaseProjectID:
        type: string # e.g. mdhs-csa-dev, mdhs-csa-isd-273818
      googleMapsKey:
        type: string
      serviceDeskKey:
        type: string
      serviceDeskURI:
        type: string
      serviceDeskID:
        type: string
      requestTypeID:
        type: string
      serviceDeskEnv:
        type: string
    steps:
      - checkout
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run: cd functions && npm ci
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - functions/node_modules
      - run:
          name: "Add env variables to functions folder"
          command: cd functions && echo
            "GOOGLE_MAPS_KEY=${<< parameters.googleMapsKey >>}

            SERVICE_DESK_KEY=${<< parameters.serviceDeskKey >>}

            SERVICE_DESK_URI=${<< parameters.serviceDeskURI >>}

            SERVICE_DESK_ID=${<< parameters.serviceDeskID >>}

            REQUEST_TYPE_ID=${<< parameters.requestTypeID >>}

            SERVICE_DESK_ENV=${<< parameters.serviceDeskEnv >>}" > .env

      - run: sudo npm install -g firebase-tools
      - run: firebase deploy -P ${<< parameters.firebaseProjectID >>} --only functions --token $FIREBASE_DEPLOY_TOKEN

  deploy_hosting_test_harness:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/repo/
    parameters:
      firebaseProjectID:
        type: string # e.g. mdhs-csa-dev, mdhs-csa-isd-273818
      googleMapsKey:
        type: string
      eventUrl:
        type: string
      textUrl:
        type: string
      feedbackURL:
        type: string
      testHarnessHostedUrl:
        type: string
    steps:
      - checkout
      - run:
          name: "Add npmrc to interface folder"
          command: cd interface && echo "${ALL_NPM_AUTH_TOKEN}" > .npmrc
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run: cd interface && npm ci
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - interface/node_modules
      - run:
          name: "Add env variables to interface folder"
          command: cd interface && echo
            "REACT_APP_GOOGLE_MAPS_KEY=${<< parameters.googleMapsKey >>}

            REACT_APP_EVENT_URL=<< parameters.eventUrl >>

            REACT_APP_TEXT_URL=<< parameters.textUrl >>

            REACT_APP_FEEDBACK_URL=<< parameters.feedbackURL >>" > .env

      - run:
          name: "Add env variables to interface folder"
          command: cd interface && npm run build
      - run: sudo npm install -g firebase-tools
      - run: firebase target:apply hosting testHarness ${<< parameters.testHarnessHostedUrl >>} -P ${<< parameters.firebaseProjectID >>} --token $FIREBASE_DEPLOY_TOKEN
      - run: firebase deploy -P ${<< parameters.firebaseProjectID >>} --only hosting:testHarness --token $FIREBASE_DEPLOY_TOKEN

  deploy_hosting_analytics:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/repo/
    parameters:
      firebaseProjectId:
        type: string
      firebaseApiKey:
        type: string
      firebaseAuthDomain:
        type: string
      firebaseDatabaseUrl:
        type: string
      firebaseDeployToken:
        type: string
      firebaseMessagingSenderId:
        type: string
      firebaseStorageBucket:
        type: string
      firebaseAppId:
        type: string
      downloadExportUrl:
        type: string
      analyticsHostedUrl:
        type: string
    steps:
      - checkout
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run: npm ci
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - node_modules
            - functions/node_modules
      - run:
          name: "Add env variables & build"
          command: |
            export REACT_APP_FIREBASE_API_KEY=${<< parameters.firebaseApiKey >>}
            export REACT_APP_FIREBASE_AUTH_DOMAIN=${<< parameters.firebaseAuthDomain >>}
            export REACT_APP_FIREBASE_DATABASE_URL=${<< parameters.firebaseDatabaseUrl >>}
            export REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${<< parameters.firebaseMessagingSenderId >>}
            export REACT_APP_FIREBASE_PROJECT_ID=${<< parameters.firebaseProjectId >>}
            export REACT_APP_FIREBASE_STORAGE_BUCKET=${<< parameters.firebaseStorageBucket >>}
            export REACT_APP_FIREBASE_APP_ID=${<< parameters.firebaseAppId >>}
            export REACT_APP_DOWNLOAD_EXPORT_FUNCTION_URL=${<< parameters.downloadExportUrl >>}
            CI=false npm run build
      - run: sudo npm install -g firebase-tools
      - run: firebase target:apply hosting analytics ${<< parameters.analyticsHostedUrl >>} -P ${<< parameters.firebaseProjectID >>} --token $FIREBASE_DEPLOY_TOKEN
      - run: firebase deploy -P ${<< parameters.firebaseProjectId >>} --only hosting:analytics --token ${<< parameters.firebaseDeployToken >>}

workflows:
  version: 2
  build_deploy:
    jobs:
      # Development Jobs
      - deploy_dialogflow_agent:
          jsonKey: DEV_MDHS_CSA_KEY_JSON
          env: dev
          filters:
            branches:
              only:
                - development
      - deploy_functions:
          firebaseProjectID: DEV_FIREBASE_PROJECT_ID
          googleMapsKey: DEV_GOOGLE_MAPS_KEY
          serviceDeskKey: DEV_SERVICE_DESK_KEY
          serviceDeskURI: DEV_SERVICE_DESK_URI
          serviceDeskID: DEV_SERVICE_DESK_ID
          requestTypeID: DEV_REQUEST_TYPE_ID
          serviceDeskEnv: DEV_SERVICE_DESK_ENV
          filters:
            branches:
              only:
                - development
      - deploy_hosting_test_harness:
          firebaseProjectID: DEV_FIREBASE_PROJECT_ID
          googleMapsKey: DEV_GOOGLE_MAPS_KEY
          eventUrl: https://us-central1-mdhs-csa-dev.cloudfunctions.net/eventRequest
          textUrl: https://us-central1-mdhs-csa-dev.cloudfunctions.net/textRequest
          feedbackURL: https://us-central1-mdhs-csa-dev.cloudfunctions.net/storeFeedback
          filters:
            branches:
              only:
                - development
      - deploy_hosting_analytics:
          firebaseProjectId: DEV_FIREBASE_PROJECT_ID
          firebaseApiKey: DEV_FIREBASE_API_KEY
          firebaseAuthDomain: DEV_FIREBASE_AUTH_DOMAIN
          firebaseDatabaseUrl: DEV_FIREBASE_DATABASE_URL
          firebaseDeployToken: DEV_FIREBASE_DEPLOY_TOKEN
          firebaseMessagingSenderId: DEV_FIREBASE_MESSAGING_SENDER_ID
          firebaseStorageBucket: DEV_FIREBASE_STORAGE_BUCKET
          firebaseAppId: DEV_FIREBASE_APP_ID
          downloadExportUrl: DEV_DOWNLOAD_EXPORT_FUNCTION_URL
          filters:
            branches:
              only:
                - development
      # ISD Jobs
      - deploy_dialogflow_agent:
          jsonKey: ISD_MDHS_CSA_KEY_JSON
          env: isd
          filters:
            branches:
              only:
                - isd
      - deploy_functions:
          firebaseProjectID: ISD_FIREBASE_PROJECT_ID
          googleMapsKey: STAGE_GOOGLE_MAPS_KEY
          serviceDeskKey: DEV_SERVICE_DESK_KEY
          serviceDeskURI: DEV_SERVICE_DESK_URI
          serviceDeskID: DEV_SERVICE_DESK_ID
          requestTypeID: DEV_REQUEST_TYPE_ID
          serviceDeskEnv: DEV_SERVICE_DESK_ENV
          filters:
            branches:
              only:
                - isd
      - deploy_hosting_test_harness:
          firebaseProjectID: ISD_FIREBASE_PROJECT_ID
          googleMapsKey: STAGE_GOOGLE_MAPS_KEY
          eventUrl: https://us-central1-mdhs-csa-isd-273818.cloudfunctions.net/eventRequest
          textUrl: https://us-central1-mdhs-csa-isd-273818.cloudfunctions.net/textRequest
          feedbackURL: https://us-central1-mdhs-csa-isd-273818.cloudfunctions.net/storeFeedback
          filters:
            branches:
              only:
                - isd
      - deploy_hosting_analytics:
          firebaseProjectId: ISD_FIREBASE_PROJECT_ID
          firebaseApiKey: ISD_FIREBASE_API_KEY
          firebaseAuthDomain: ISD_FIREBASE_AUTH_DOMAIN
          firebaseDatabaseUrl: ISD_FIREBASE_DATABASE_URL
          firebaseDeployToken: ISD_FIREBASE_DEPLOY_TOKEN
          firebaseMessagingSenderId: ISD_FIREBASE_MESSAGING_SENDER_ID
          firebaseStorageBucket: ISD_FIREBASE_STORAGE_BUCKET
          firebaseAppId: ISD_FIREBASE_APP_ID
          downloadExportUrl: ISD_DOWNLOAD_EXPORT_FUNCTION_URL
          filters:
            branches:
              only:
                - development
      # Stage Jobs
      - deploy_dialogflow_agent:
          jsonKey: STAGE_MDHS_CSA_KEY_JSON
          env: stage
          filters:
            branches:
              only:
                - stage
      - deploy_functions:
          firebaseProjectID: STAGE_FIREBASE_PROJECT_ID
          googleMapsKey: STAGE_GOOGLE_MAPS_KEY
          serviceDeskKey: STAGE_SERVICE_DESK_KEY
          serviceDeskURI: STAGE_SERVICE_DESK_URI
          serviceDeskID: STAGE_SERVICE_DESK_ID
          requestTypeID: STAGE_REQUEST_TYPE_ID
          serviceDeskEnv: STAGE_SERVICE_DESK_ENV
          filters:
            branches:
              only:
                - stage
      - deploy_hosting_test_harness:
          firebaseProjectID: STAGE_FIREBASE_PROJECT_ID
          googleMapsKey: STAGE_GOOGLE_MAPS_KEY
          eventUrl: https://us-central1-mdhs-csa-stage.cloudfunctions.net/eventRequest
          textUrl: https://us-central1-mdhs-csa-stage.cloudfunctions.net/textRequest
          feedbackURL: https://us-central1-mdhs-csa-stage.cloudfunctions.net/storeFeedback
          filters:
            branches:
              only:
                - stage
      - deploy_hosting_analytics:
          firebaseProjectId: STAGE_FIREBASE_PROJECT_ID
          firebaseApiKey: STAGE_FIREBASE_API_KEY
          firebaseAuthDomain: STAGE_FIREBASE_AUTH_DOMAIN
          firebaseDatabaseUrl: STAGE_FIREBASE_DATABASE_URL
          firebaseDeployToken: STAGE_FIREBASE_DEPLOY_TOKEN
          firebaseMessagingSenderId: STAGE_FIREBASE_MESSAGING_SENDER_ID
          firebaseStorageBucket: STAGE_FIREBASE_STORAGE_BUCKET
          firebaseAppId: STAGE_FIREBASE_APP_ID
          downloadExportUrl: STAGE_DOWNLOAD_EXPORT_FUNCTION_URL
          filters:
            branches:
              only:
                - stage
      # Production Jobs
      - deploy_dialogflow_agent:
          jsonKey: PROD_MDHS_CSA_KEY_JSON
          env: prod
          filters:
            branches:
              only:
                - master
      - deploy_functions:
          firebaseProjectID: PROD_FIREBASE_PROJECT_ID
          googleMapsKey: PROD_GOOGLE_MAPS_KEY
          serviceDeskKey: PROD_SERVICE_DESK_KEY
          serviceDeskURI: PROD_SERVICE_DESK_URI
          serviceDeskID: PROD_SERVICE_DESK_ID
          requestTypeID: PROD_REQUEST_TYPE_ID
          serviceDeskEnv: PROD_SERVICE_DESK_ENV
          filters:
            branches:
              only:
                - master
      # We do NOT deploy the test harness hosting project for the master branch
      # a wordpress site and requires gen to be implemented via a plug in.
      - deploy_hosting_analytics:
          firebaseProjectId: PROD_FIREBASE_PROJECT_ID
          firebaseApiKey: PROD_FIREBASE_API_KEY
          firebaseAuthDomain: PROD_FIREBASE_AUTH_DOMAIN
          firebaseDatabaseUrl: PROD_FIREBASE_DATABASE_URL
          firebaseDeployToken: PROD_FIREBASE_DEPLOY_TOKEN
          firebaseMessagingSenderId: PROD_FIREBASE_MESSAGING_SENDER_ID
          firebaseStorageBucket: PROD_FIREBASE_STORAGE_BUCKET
          firebaseAppId: PROD_FIREBASE_APP_ID
          downloadExportUrl: PROD_DOWNLOAD_EXPORT_FUNCTION_URL
          filters:
            branches:
              only:
                - master
