version: 2.1
jobs:
  deploy_dialogflow_agent:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/repo/
    parameters:
      jsonKey:
        description: "The key json object specified in the environment variables."
        type: string # string? "${DEV_MDHS_CSA_KEY_JSON}"
      env:
        type: string # e.g. dev,
    steps:
      - checkout
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run: cd scripts && npm ci
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - scripts/node_modules
      - run:
          name: "Add env variables"
          command: cd scripts && echo "GOOGLE_APPLICATION_CREDENTIALS=./mdhs-key.json" > .env
      - run:
          name: "Create mdhs key file for scripts"
          command: cd scripts && echo "${<< parameters.jsonKey >>}" > mdhs-key.json
      - run:
          name: "Agent configuration"
          command: cd agent && mv agent.<< parameters.env >>.json agent.json
      - run:
          name: "Restore to << parameters.env >> Dialogflow"
          command: cd scripts && node restoreDialogflow
      - run:
          name: "Populate Firestore"
          command: cd scripts && node populateFirestore
  deploy_functions:
    docker:
      - image: circleci/node
    working_directory: ~/repo/
    parameters:
      firebaseProjectId:
        type: string # e.g. mdhs-csa-dev, mdhs-csa-isd-273818
      googleMapsKey:
        type: string
      serviceDeskKey:
        type: string
      serviceDeskURI:
        type: string
      serviceDeskID:
        type: integer
      requestTypeID:
        type: integer
      serviceDeskEnv:
        type: string
    steps:
      - checkout
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run: cd functions && npm ci
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - functions/node_modules
      - run:
          name: "Add env variables to functions folder"
          command: cd functions && echo
            "GOOGLE_MAPS_KEY=${<< parameters.googleMapsKey >>}

            SERVICE_DESK_KEY=${<< parameters.serviceDeskKey >>}

            SERVICE_DESK_URI=${<< parameters.serviceDeskURI >>}

            SERVICE_DESK_ID=${<< parameters.serviceDeskID >>}

            REQUEST_TYPE_ID=${<< parameters.requestTypeID >>}

            SERVICE_DESK_ENV=${<< parameters.serviceDeskEnv >>}" > .env

      - run: sudo npm install -g firebase-tools
      - run: firebase use ${<< parameters.firebaseProjectId >>} --token $FIREBASE_DEPLOY_TOKEN
      - run: firebase deploy --only functions --token $FIREBASE_DEPLOY_TOKEN

  deploy_hosting_test_harness:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/repo/
    parameters:
      firebaseProjectId:
        type: string # e.g. mdhs-csa-dev, mdhs-csa-isd-273818
      googleMapsKey:
        type: string
      eventUrl:
        type: string
      textUrl:
        type: string
      feedbackURL:
        type: string
      testHarnessHostedUrl:
        type: string
    steps:
      - checkout
      - run:
          name: "Add npmrc to interface folder"
          command: cd interface && echo "${ALL_NPM_AUTH_TOKEN}" > .npmrc
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run: cd interface && npm ci
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - interface/node_modules
      - run:
          name: "Add env variables to interface folder"
          command: cd interface && echo
            "REACT_APP_GOOGLE_MAPS_KEY=${<< parameters.googleMapsKey >>}

            REACT_APP_EVENT_URL=<< parameters.eventUrl >>

            REACT_APP_TEXT_URL=<< parameters.textUrl >>

            REACT_APP_FEEDBACK_URL=<< parameters.feedbackURL >>" > .env

      - run:
          name: "Add env variables to interface folder"
          command: cd interface && npm run build
      - run: sudo npm install -g firebase-tools
      - run: firebase use ${<< parameters.firebaseProjectId >>} --token $FIREBASE_DEPLOY_TOKEN
      - run: firebase target:apply hosting testHarness ${<< parameters.testHarnessHostedUrl >>} --token $FIREBASE_DEPLOY_TOKEN
      - run: firebase deploy --only hosting:testHarness --token $FIREBASE_DEPLOY_TOKEN

  deploy_hosting_analytics:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/repo/
    parameters:
      firebaseProjectId:
        type: string
      firebaseApiKey:
        type: string
      firebaseAuthDomain:
        type: string
      firebaseDatabaseUrl:
        type: string
      firebaseMessagingSenderId:
        type: integer
      firebaseStorageBucket:
        type: string
      firebaseAppId:
        type: string
      downloadExportUrl:
        type: string
      analyticsHostedUrl:
        type: string
    steps:
      - checkout
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run: npm ci
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - node_modules
            - functions/node_modules
      - run:
          name: "Add env variables & build"
          command: |
            export REACT_APP_FIREBASE_API_KEY=${<< parameters.firebaseApiKey >>}
            export REACT_APP_FIREBASE_AUTH_DOMAIN=${<< parameters.firebaseAuthDomain >>}
            export REACT_APP_FIREBASE_DATABASE_URL=${<< parameters.firebaseDatabaseUrl >>}
            export REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${<< parameters.firebaseMessagingSenderId >>}
            export REACT_APP_FIREBASE_PROJECT_ID=${<< parameters.firebaseProjectId >>}
            export REACT_APP_FIREBASE_STORAGE_BUCKET=${<< parameters.firebaseStorageBucket >>}
            export REACT_APP_FIREBASE_APP_ID=${<< parameters.firebaseAppId >>}
            export REACT_APP_DOWNLOAD_EXPORT_FUNCTION_URL=${<< parameters.downloadExportUrl >>}
            CI=false npm run build
      - run: sudo npm install -g firebase-tools
      - run: firebase use ${<< parameters.firebaseProjectId >>} --token $FIREBASE_DEPLOY_TOKEN
      - run: firebase target:apply hosting analytics ${<< parameters.analyticsHostedUrl >>} --token $FIREBASE_DEPLOY_TOKEN
      - run: firebase deploy --only hosting:analytics --token $FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2
  build_deploy:
    jobs:
      # Development Jobs
      - deploy_dialogflow_agent:
          jsonKey: DEV_MDHS_CSA_KEY_JSON
          env: dev
          filters:
            branches:
              only:
                - development
      - deploy_functions:
          firebaseProjectId: mdhs-csa-dev
          googleMapsKey: AIzaSyCSpN9JJqwyhOXPJ9qtLsaN0DlkLcEpO2Y # Not a secret
          serviceDeskKey: SERVICE_DESK_KEY
          serviceDeskURI: https://msdhs.atlassian.net/rest/servicedeskapi/request
          serviceDeskID: 7
          requestTypeID: 75
          serviceDeskEnv: Test
          filters:
            branches:
              only:
                - development
      - deploy_hosting_test_harness:
          firebaseProjectId: mdhs-csa-dev
          googleMapsKey: AIzaSyCSpN9JJqwyhOXPJ9qtLsaN0DlkLcEpO2Y # Not a secret
          eventUrl: https://us-central1-mdhs-csa-dev.cloudfunctions.net/eventRequest
          textUrl: https://us-central1-mdhs-csa-dev.cloudfunctions.net/textRequest
          feedbackURL: https://us-central1-mdhs-csa-dev.cloudfunctions.net/storeFeedback
          testHarnessHostedUrl: mdhs-csa-dev-test-harness
          filters:
            branches:
              only:
                - development
      - deploy_hosting_analytics:
          firebaseProjectId: mdhs-csa-dev
          firebaseApiKey: AIzaSyDGkhs6juNsvEBN6c1aNpbGIPcZhB2dImM # Not a secret
          firebaseAuthDomain: mdhs-csa-dev.firebaseapp.com
          firebaseDatabaseUrl: https://mdhs-csa-dev.firebaseio.com
          firebaseStorageBucket: mdhs-csa-dev.appspot.com
          firebaseMessagingSenderId: 390034944383
          firebaseAppId: 1:390034944383:web:6cefab99af945d7876aa4a
          downloadExportUrl: https://us-central1-mdhs-csa-dev.cloudfunctions.net/downloadExport
          analyticsHostedUrl: mdhs-csa-dev-analytics
          filters:
            branches:
              only:
                - development
      # ISD Jobs
      - deploy_dialogflow_agent:
          jsonKey: ISD_MDHS_CSA_KEY_JSON
          env: isd
          filters:
            branches:
              only:
                - isd
      - deploy_functions:
          firebaseProjectId: mdhs-csa-isd-273818
          googleMapsKey: AIzaSyCSpN9JJqwyhOXPJ9qtLsaN0DlkLcEpO2Y # Not a secret
          serviceDeskKey: SERVICE_DESK_KEY
          serviceDeskURI: https://msdhs.atlassian.net/rest/servicedeskapi/request
          serviceDeskID: 7
          requestTypeID: 75
          serviceDeskEnv: Test
          filters:
            branches:
              only:
                - isd
      - deploy_hosting_test_harness:
          firebaseProjectId: mdhs-csa-isd-273818
          googleMapsKey: AIzaSyCSpN9JJqwyhOXPJ9qtLsaN0DlkLcEpO2Y # Not a secret
          eventUrl: https://us-central1-mdhs-csa-isd-273818.cloudfunctions.net/eventRequest
          textUrl: https://us-central1-mdhs-csa-isd-273818.cloudfunctions.net/textRequest
          feedbackURL: https://us-central1-mdhs-csa-isd-273818.cloudfunctions.net/storeFeedback
          testHarnessHostedUrl: tbd
          filters:
            branches:
              only:
                - isd
      - deploy_hosting_analytics:
          firebaseProjectId: mdhs-csa-isd-273818
          firebaseApiKey: AIzaSyAZecCjFe--9pJh2hIo6FADebDBHg7RK6M # Not a secret
          firebaseAuthDomain: mdhs-csa-isd-273818.firebaseapp.com
          firebaseDatabaseUrl: https://mdhs-csa-isd-273818.firebaseio.com
          firebaseStorageBucket: mdhs-csa-isd-273818.appspot.com
          firebaseMessagingSenderId: 982471055822
          firebaseAppId: 1:982471055822:web:65ee3d09dd3e1e0822f39f
          downloadExportUrl: https://us-central1-mdhs-csa-isd-273818.cloudfunctions.net/downloadExport
          analyticsHostedUrl: tbd
          filters:
            branches:
              only:
                - isd
      # Stage Jobs
      - deploy_dialogflow_agent:
          jsonKey: STAGE_MDHS_CSA_KEY_JSON
          env: stage
          filters:
            branches:
              only:
                - stage
      - deploy_functions:
          firebaseProjectId: mdhs-csa-stage
          googleMapsKey: AIzaSyCSpN9JJqwyhOXPJ9qtLsaN0DlkLcEpO2Y # Not a secret
          serviceDeskKey: SERVICE_DESK_KEY
          serviceDeskURI: https://msdhs.atlassian.net/rest/servicedeskapi/request
          serviceDeskID: 7
          requestTypeID: 75
          serviceDeskEnv: Test
          filters:
            branches:
              only:
                - stage
      - deploy_hosting_test_harness:
          firebaseProjectId: mdhs-csa-stage
          googleMapsKey: AIzaSyCSpN9JJqwyhOXPJ9qtLsaN0DlkLcEpO2Y # Not a secret
          eventUrl: https://us-central1-mdhs-csa-stage.cloudfunctions.net/eventRequest
          textUrl: https://us-central1-mdhs-csa-stage.cloudfunctions.net/textRequest
          feedbackURL: https://us-central1-mdhs-csa-stage.cloudfunctions.net/storeFeedback
          testHarnessHostedUrl: tbd
          filters:
            branches:
              only:
                - stage
      - deploy_hosting_analytics:
          firebaseProjectId: mdhs-csa-stage
          firebaseApiKey: AIzaSyAXH0VmURgNJu21ueoep22rmgpe7dZozUU # Not a secret
          firebaseAuthDomain: mdhs-csa-stage.firebaseapp.com
          firebaseDatabaseUrl: https://mdhs-csa-stage.firebaseio.co
          firebaseStorageBucket: mdhs-csa-stage.appspot.com
          firebaseMessagingSenderId: 75224097502
          firebaseAppId: 1:75224097502:web:43ecc962b205e01b37584f
          downloadExportUrl: https://us-central1-mdhs-csa-stage.cloudfunctions.net/downloadExport
          analyticsHostedUrl: tbd
          filters:
            branches:
              only:
                - stage
      # Production Jobs
      - deploy_dialogflow_agent:
          jsonKey: PROD_MDHS_CSA_KEY_JSON
          env: prod
          filters:
            branches:
              only:
                - master
      - deploy_functions:
          firebaseProjectId: mdhs-csa
          googleMapsKey: AIzaSyCSpN9JJqwyhOXPJ9qtLsaN0DlkLcEpO2Y # Not a secret
          serviceDeskKey: SERVICE_DESK_KEY
          serviceDeskURI: https://msdhs.atlassian.net/rest/servicedeskapi/request
          serviceDeskID: 7
          requestTypeID: 75
          serviceDeskEnv: Production
          filters:
            branches:
              only:
                - master
      # We do NOT deploy the test harness hosting project for the master branch
      # a wordpress site and requires gen to be implemented via a plug in.
      - deploy_hosting_analytics:
          firebaseProjectId: mdhs-csa
          firebaseApiKey: AIzaSyC1Kxwy-RmgB8k80i-xrcMVya_5uE2-sDM # Not a secret
          firebaseAuthDomain: mdhs-csa.firebaseapp.com
          firebaseDatabaseUrl: https://mdhs-csa.firebaseio.com
          firebaseStorageBucket: mdhs-csa.appspot.com
          firebaseMessagingSenderId: 804026557045
          firebaseAppId: 1:804026557045:web:501111adde1bda8c87ce3c
          downloadExportUrl: https://us-central1-mdhs-csa.cloudfunctions.net/downloadExport
          analyticsHostedUrl: tbd
          filters:
            branches:
              only:
                - master
