version: 2
jobs:
  deploy_dev_functions:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/repo/
    steps:
      - checkout
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run: cd functions && npm install
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - functions/node_modules
      - run:
          name: 'Add env variables and deploy'
          command: |
            cd functions && echo "GOOGLE_MAPS_KEY=${DEV_GOOGLE_MAPS_KEY} \n SERVICE_DESK_KEY=${DEV_SERVICE_DESK_KEY} \n SERVICE_DESK_URI=${DEV_SERVICE_DESK_URI} \n SERVICE_DESK_ID=${DEV_SERVICE_DESK_ID} \n REQUEST_TYPE_ID=${DEV_REQUEST_TYPE_ID} \n SERVICE_DESK_ENV=${DEV_SERVICE_DESK_ENV} \n ANALYTICS_URI=${DEV_ANALYTICS_URI}" > .env
      - run: sudo npm install -g firebase-tools
      - run: firebase deploy -P $DEV_FIREBASE_PROJECT_ID --only functions --token $FIREBASE_DEPLOY_TOKEN
workflows:
  version: 2
  build_deploy:
    jobs:
      - deploy_dev_functions:
          filters:
            branches:
              only:
                - development
