version: 2
jobs:
  deploy_functions:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/repo/
    steps:
      - checkout
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: 'Add env variables and deploy'
          command: |
            export GOOGLE_MAPS_KEY=$GOOGLE_MAPS_KEY
            export SERVICE_DESK_KEY=$SERVICE_DESK_KEY
            export SERVICE_DESK_URI=$SERVICE_DESK_URI
            export SERVICE_DESK_ID=$SERVICE_DESK_ID
            export REQUEST_TYPE_ID=$REQUEST_TYPE_ID
            export SERVICE_DESK_ENV=$SERVICE_DESK_ENV
      - run: sudo npm install -g firebase-tools
      - run: firebase deploy -P $FIREBASE_PROJECT_ID --only functions --token $FIREBASE_DEPLOY_TOKEN
workflows:
  version: 2
  build_deploy:
    jobs:
      - deploy_functions:
          filters:
            branches:
              only:
                - development
