// This function imports several packages in order to reduce the chances
// of a user cold starting the fulfillment function in PROD. Since packages
// are cached after importing the first time in each instance,
// importing them like this once every few minutes should reduce the likelihood
// of a user encountering a cold start
// ALSO, this file is JS and not TS because we want to turn off typescript errors for unused 
// variables in this file only, not in all files.
export const importPackages = async () => {
  const { WebhookClient } = require('dialogflow-fulfillment')
  const getSubjectMatter = require('./getSubjectMatter')
  const { subjectMatterLocations } = require('../constants/constants')
  const { getTextResponses, getSuggestions, genericHandler, shouldHandleEndConversation } = require('./fulfillmentMessages.js')

  const { welcome } = await import('../intentHandlers/globalFunctions')
  const { acknowledgePrivacyStatement } = await import('../intentHandlers/globalFunctions')
  const { globalRestart } = await import('../intentHandlers/globalFunctions')
  const { restartConversation } = await import('../intentHandlers/globalFunctions')
  const { caseyHandoff } = await import('../intentHandlers/globalFunctions')
  const { setContext } = await import('../intentHandlers/globalFunctions')

  // START COMMON
  const { noneOfThese } = await import('../intentHandlers/common/commonFallback')
  const { commonFallback } = await import('../intentHandlers/common/commonFallback')
  const { docUpload } = await import('../intentHandlers/common/docUpload')
  const { feedbackRoot } = await import('../intentHandlers/common/feedback')
  const { feedbackHelpful } = await import('../intentHandlers/common/feedback')
  const { feedbackNotHelpful } = await import('../intentHandlers/common/feedback')
  const { feedbackComplete } = await import('../intentHandlers/common/feedback')
  const { mapDeliverMap, mapRoot } = await import('../intentHandlers/common/map')
  const { mapDeliverMapAndCountyOffice } = await import('../intentHandlers/common/map')
  const { eligibilityChecker } = await import('../intentHandlers/common/eligibilityChecker')
  const { pebtRoot } = await import('../intentHandlers/common/pebt')

  // START CSE
  const { contactSupportHandoff } = await import('../intentHandlers/childSupport/contactQA')
  const { pmtCalcRoot } = await import('../intentHandlers/childSupport/paymentsCalculator')
  const { pmtCalcRootRestart } = await import('../intentHandlers/childSupport/paymentsCalculator')
  const { pmtCalcIncomeTerm } = await import('../intentHandlers/childSupport/paymentsCalculator')
  const { pmtCalcGrossIncome } = await import('../intentHandlers/childSupport/paymentsCalculator')
  const { pmtCalcTaxDeductions } = await import('../intentHandlers/childSupport/paymentsCalculator')
  const { pmtCalcSSDeductions } = await import('../intentHandlers/childSupport/paymentsCalculator')
  const { pmtCalcRetirementContributions } = await import('../intentHandlers/childSupport/paymentsCalculator')
  const { pmtCalcChildSupport } = await import('../intentHandlers/childSupport/paymentsCalculator')
  const { pmtCalcChildSupportNoRetirement } = await import('../intentHandlers/childSupport/paymentsCalculator')
  const { pmtCalcFinalEstimation } = await import('../intentHandlers/childSupport/paymentsCalculator')
  const { pmtCalcFinalEstimationNoOtherChildren } = await import('../intentHandlers/childSupport/paymentsCalculator')
  const { iwoConfirmEstimate } = await import('../intentHandlers/childSupport/incomeWithholding')
  const { iwoIsSupporting } = await import('../intentHandlers/childSupport/incomeWithholding')
  const { iwoInArrears } = await import('../intentHandlers/childSupport/incomeWithholding')
  const { iwoDisposableIncome } = await import('../intentHandlers/childSupport/incomeWithholding')
  const { iwoQAArrearsBalance } = await import('../intentHandlers/childSupport/incomeWithholding')
  const { pmtMethodsCheckOrMoneyOrder } = await import('../intentHandlers/childSupport/paymentMethods')
  const { pmtMethodsMailAddress } = await import('../intentHandlers/childSupport/paymentMethods')
  const { pmtMethodsCantMakeQualifying } = await import('../intentHandlers/childSupport/paymentMethods')
  const { pmtMethodsCantMakeQualifyingHelp } = await import('../intentHandlers/childSupport/paymentMethods')
  const { pmtMethodsCantMakeQualifyingNoHelp } = await import('../intentHandlers/childSupport/paymentMethods')
  const { closeCSCQACloseCase } = await import('../intentHandlers/childSupport/closeChildSupportCase')
  const { apptsOfficeLocationsHandoff } = await import('../intentHandlers/childSupport/appointments')
  const { supportRoot } = await import('../intentHandlers/childSupport/support')
  const { supportParentPayingMore } = await import('../intentHandlers/childSupport/support')
  const { supportParentReceivingMore } = await import('../intentHandlers/childSupport/support')
  const { supportHandleEmploymentStatus } = await import('../intentHandlers/childSupport/support')
  const { supportCollectNewEmployerName } = await import('../intentHandlers/childSupport/support')
  const { supportNoNewEmployer } = await import('../intentHandlers/childSupport/support')
  const { supportNewEmployerUnknownPhone } = await import('../intentHandlers/childSupport/support')
  const { supportCollectNewEmployerPhone } = await import('../intentHandlers/childSupport/support')
  const { supportType } = await import('../intentHandlers/childSupport/support')
  const { supportCollectCompanyName } = await import('../intentHandlers/childSupport/support')
  const { supportCollectFirstName } = await import('../intentHandlers/childSupport/support')
  const { supportCollectLastName } = await import('../intentHandlers/childSupport/support')
  const { supportPhoneNumber } = await import('../intentHandlers/childSupport/support')
  const { supportNoPhoneNumber } = await import('../intentHandlers/childSupport/support')
  const { supportEmail } = await import('../intentHandlers/childSupport/support')
  const { supportNoEmail } = await import('../intentHandlers/childSupport/support')
  const { supportHandleEmailRetry } = await import('../intentHandlers/childSupport/support')
  const { supportHandlePhoneRetry } = await import('../intentHandlers/childSupport/support')
  const { supportCaseNumber } = await import('../intentHandlers/childSupport/support')
  const { supportNoCaseNumber } = await import('../intentHandlers/childSupport/support')
  const { supportCollectIssue } = await import('../intentHandlers/childSupport/support')
  const { supportSubmitIssue } = await import('../intentHandlers/childSupport/support')
  const { supportEditProviderEmployment } = await import('../intentHandlers/childSupport/support')
  const { supportReportProviderEmployment } = await import('../intentHandlers/childSupport/support')
  const { supportSubmitSupportRequestCooperation } = await import('../intentHandlers/childSupport/support')
  const { supportSubmitSupportRequestInquiry } = await import('../intentHandlers/childSupport/support')
  const { supportSubmitSupportRequestSafety } = await import('../intentHandlers/childSupport/support')
  const { supportSubmitSupportRequestGoodCause } = await import('../intentHandlers/childSupport/support')
  const { supportSubmitSupportRequestVerification } = await import('../intentHandlers/childSupport/support')
  const { supportSubmitSupportRequestInterstate } = await import('../intentHandlers/childSupport/support')
  const { supportSubmitSupportRequestRequestPaymentHistory } = await import('../intentHandlers/childSupport/support')
  const { caseQAIncreaseReview } = await import('../intentHandlers/childSupport/caseQA')
  const { caseQAChangePersonalInfo } = await import('../intentHandlers/childSupport/caseQA')
  const { caseQAComplianceSupportRequest } = await import('../intentHandlers/childSupport/caseQA')
  const { eppiFees } = await import('../intentHandlers/childSupport/eppiCard')
  const { pmtQAHaventReceived } = await import('../intentHandlers/childSupport/paymentsQA')
  const { pmtQAPaymentReduction } = await import('../intentHandlers/childSupport/paymentsQA')
  const { pmtQAYesPaymentReduction } = await import('../intentHandlers/childSupport/paymentsQA')
  const { pmtQAOver21 } = await import('../intentHandlers/childSupport/paymentsQA')
  const { pmtQAEmployerPaymentStatus } = await import('../intentHandlers/childSupport/paymentsQA')
  const { pmtQAYesEmployerPaymentStatus } = await import('../intentHandlers/childSupport/paymentsQA')
  const { pmtQANCPPaymentStatus } = await import('../intentHandlers/childSupport/paymentsQA')
  const { childCare } = await import('../intentHandlers/childSupport/childCare')
  const { fee } = await import('../intentHandlers/childSupport/fee')
  const { legal } = await import('../intentHandlers/childSupport/legal')

  // START TANF
  const { tanfRoot } = await import('../intentHandlers/tanf/tanfRoot')

  // START SNAP
  const { snapRoot } = await import('../intentHandlers/snap/snapRoot')
}